spring:
  application:
    name: ms-accesorios
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:mysql://localhost:3307/db_accesorios?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    deserialization:
      fail-on-null-for-primitives: true

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - java.lang.IllegalArgumentException
          - pe.edu.upeu.msaccesorios.errors.AccesorioNotFoundException
          - pe.edu.upeu.msaccesorios.errors.ValidationException
    instances:
      accesorioService:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        baseConfig: default
        ignoreExceptions:
          - java.lang.IllegalArgumentException
          - pe.edu.upeu.msaccesorios.errors.AccesorioNotFoundException
          - pe.edu.upeu.msaccesorios.errors.ValidationException